networks: 
  local:
    driver: bridge

services:

  mongodb:
    container_name: mongodb
    networks:
      - local
    image: mongo

  api:
    container_name: api
    networks: 
      - local
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/usr/src/app
    working_dir: /usr/src/app
    links:
      - mongodb